//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WPF.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to broj.
        /// </summary>
        public static string broj {
            get {
                return ResourceManager.GetString("broj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Da.
        /// </summary>
        public static string da {
            get {
                return ResourceManager.GetString("da", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalji.
        /// </summary>
        public static string detalji {
            get {
                return ResourceManager.GetString("detalji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en.
        /// </summary>
        public static string en {
            get {
                return ResourceManager.GetString("en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fifaCode.
        /// </summary>
        public static string fifaCode {
            get {
                return ResourceManager.GetString("fifaCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to format.
        /// </summary>
        public static string format {
            get {
                return ResourceManager.GetString("format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to golovi.
        /// </summary>
        public static string golovi {
            get {
                return ResourceManager.GetString("golovi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hr.
        /// </summary>
        public static string hr {
            get {
                return ResourceManager.GetString("hr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to igracInfo.
        /// </summary>
        public static string igrac {
            get {
                return ResourceManager.GetString("igrac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ime.
        /// </summary>
        public static string ime {
            get {
                return ResourceManager.GetString("ime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jezik.
        /// </summary>
        public static string jezik {
            get {
                return ResourceManager.GetString("jezik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kapetan.
        /// </summary>
        public static string kapetan {
            get {
                return ResourceManager.GetString("kapetan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kartoni.
        /// </summary>
        public static string kartoni {
            get {
                return ResourceManager.GetString("kartoni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to muško.
        /// </summary>
        public static string musko {
            get {
                return ResourceManager.GetString("musko", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to naziv.
        /// </summary>
        public static string naziv {
            get {
                return ResourceManager.GetString("naziv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ne.
        /// </summary>
        public static string ne {
            get {
                return ResourceManager.GetString("ne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neodluceno.
        /// </summary>
        public static string neodluceno {
            get {
                return ResourceManager.GetString("neodluceno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pitanje.
        /// </summary>
        public static string pitanjeIzlazak {
            get {
                return ResourceManager.GetString("pitanjeIzlazak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pobjede.
        /// </summary>
        public static string pobjede {
            get {
                return ResourceManager.GetString("pobjede", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial Settings.
        /// </summary>
        public static string PocetnePostavke {
            get {
                return ResourceManager.GetString("PocetnePostavke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Porazi.
        /// </summary>
        public static string porazi {
            get {
                return ResourceManager.GetString("porazi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postavke.
        /// </summary>
        public static string postavke {
            get {
                return ResourceManager.GetString("postavke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potvrdi.
        /// </summary>
        public static string Potvrdi {
            get {
                return ResourceManager.GetString("Potvrdi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pozicija.
        /// </summary>
        public static string pozicija {
            get {
                return ResourceManager.GetString("pozicija", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primljeni.
        /// </summary>
        public static string primljeni {
            get {
                return ResourceManager.GetString("primljeni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to prvenstvo.
        /// </summary>
        public static string prvenstvo {
            get {
                return ResourceManager.GetString("prvenstvo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Razlika.
        /// </summary>
        public static string razlika {
            get {
                return ResourceManager.GetString("razlika", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj utakmica.
        /// </summary>
        public static string utakmice {
            get {
                return ResourceManager.GetString("utakmice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zabijeni.
        /// </summary>
        public static string zabijeni {
            get {
                return ResourceManager.GetString("zabijeni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zatvaranje.
        /// </summary>
        public static string zatvaranje {
            get {
                return ResourceManager.GetString("zatvaranje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to žensko.
        /// </summary>
        public static string zensko {
            get {
                return ResourceManager.GetString("zensko", resourceCulture);
            }
        }
    }
}
